spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        encrypt:
          # We will send encrypted properties
          enabled: false
        git:
          uri: https://github.com/doctore/Spring5Microservices_ConfigServerData.git
          searchPaths: gateway-server,pizza-service,order-service,security-jwt-service,security-oauth-service
          defaultLabel: master